

```{r, results = "hide", message = FALSE}
## read fam file with qn trait values for all subjects & all traits
fam_all <- vroom::vroom(here::here("dat", paste0("hsq", hsq, "_pcausal", pc), "sim_traits", "fam_all_subjects", paste0("qn_traits_all_subjects_hsq", h2, "_pcausal", pc, ".fam")), col_names = FALSE)
##
phe_num <- x
fam_file <- here::here("dat", paste0("hsq", hsq, "_pcausal", pc), "gemma", "chr1.fam")
  # read fam file
fam <- readr::read_table(file = fam_file, col_names = FALSE)
for (cross_num in 1:5){
  ## define col_num
  #col_num <- phe_num * 5 + (cross_num %% 5) + 1 
  col_num <- phe_num + 5
  ## 
  fam2 <- fam_all %>%
    dplyr::select(1, 2, dplyr::all_of(col_num)) 
  # read the profile files outputted by plink score allele
  scores <- list()
  for (chr_num in 1:22){
    pfn <- paste0("pred_ukb_pheno", 
                 phe_num, 
                 "_fold", 
                 cross_num, 
                 "_chr", 
                 chr_num, 
                 "_best.dbslmm.txt.profile")
    
    profile_fn <- here::here("dat", paste0("hsq", hsq, "_pcausal", pc), "DBSLMM", pfn)
    scores[[chr_num]] <- readr::read_table(profile_fn, col_names = TRUE)
    colnames(scores[[chr_num]]) <- paste0(colnames(scores[[chr_num]]), "_chr", chr_num)
  }
  scores2 <- lapply(X = scores, FUN = function(x){
    x %>% dplyr::select(6) # choose the SCORESUM column
  })
  scores_df <- do.call("cbind", scores2) %>% tibble::as_tibble() %>%
    dplyr::mutate(sum_scores = rowSums(.))
  s2 <- scores_df %>%
    dplyr::select(sum_scores)
  # read idx file
  idx_fn <- here::here("dat", paste0("hsq", hsq, "_pcausal", pc), paste0("test-ids-fold", cross_num, ".txt")) 
  idx <- readr::read_table(idx_fn, col_names = FALSE) %>%
    dplyr::rename(fam_id = 1, subject_id = 2) %>%
    dplyr::select(fam_id)
  fam3 <- fam2 %>%
    dplyr::rename(fam_id = 1) %>%
    dplyr::right_join(idx, by = "fam_id") %>%
    dplyr::mutate(predicted_value = s2$sum_scores) 
  out[[cross_num]] <- fam3 %>%
    dplyr::rename(true_pheno = 3) %>%
    dplyr::mutate(cross_membership = cross_num)
}  
```

```{r}
out_tib <- do.call("rbind", out) %>% 
  tibble::as_tibble() %>% 
  dplyr::mutate(residual = abs(true_pheno - predicted_value))
```

Now, we read in the plink score outputs and sum to get predicted values for the 
subjects belonging to the verification set.


```{r, results='hide', message = FALSE}
verif_ids_fn <- here::here("dat", paste0("hsq", hsq, "_pcausal", pc), "verification-ids.txt")
verif_ids <- vroom::vroom(verif_ids_fn, col_names = TRUE)
verif_fn <- here::here("dat", paste0("hsq", hsq, "_pcausal", pc), "verification", paste0("pheno", phe_num, "_hsq", hsq, "_pcausal", pc,".txt"))
# above file contains phenotype values for the verification set
verification_true_pheno_tib <- readr::read_table(verif_fn, col_names = FALSE) %>%
  dplyr::bind_cols(verif_ids) %>%
  dplyr::rename(fam_id = 2, true_pheno = 1, subject_id = 3) %>%
  dplyr::select(2,3,1)
```

```{r}

# get the five versions of predicted values for the verification set subjects
out <- list()
for (cross_num in 1:5){
  foo <- list()
  for (chr_num in 1:22){
    fn <- here::here("dat", paste0("hsq", hsq, "_pcausal", pc), "verification", paste0("allele-scores_hsq", h2, "_pcausal", pc), paste0("pred_ukb_pheno", phe_num, "_fold", cross_num, "_chr", chr_num, "_best.dbslmm.txt.profile"))
    foo[[chr_num]] <- readr::read_table(fn) 
  }
  out[[cross_num]] <- foo 
}
# sum for each cross num
pred_vals_verification_set <- list()
for (cross_num in 1:5){
  # rename cols in each list's elements (tibbles)
  s2 <- list()
  for (chr_num in 1:22){
    s2[[chr_num]] <- out[[cross_num]][[chr_num]] %>%
      dplyr::select(6)  # choose only the SCORESUM column
      colnames(s2[[chr_num]]) <- paste0(colnames(s2[[chr_num]]), "_chr", chr_num) 
  }
  scores_df <- do.call("cbind", s2) %>% 
    tibble::as_tibble() %>%
    dplyr::mutate(sum_scores = rowSums(.)) %>%
    dplyr::select(sum_scores) %>%
    dplyr::rename(predicted_value = sum_scores)
  colnames(scores_df) <- paste0(colnames(scores_df), "_cross", cross_num)
  pred_vals_verification_set[[cross_num]] <- scores_df
}
pred_vals_verification_set_tib <- do.call("cbind", pred_vals_verification_set) %>%
  tibble::as_tibble() %>%
  dplyr::mutate(true_pheno = verification_true_pheno_tib$true_pheno)
```



```{r, message = FALSE}
get_fitted <- function(index, fitted_vec){
  fitted_vec[index]
}

n_verification <- nrow(pred_vals_verification_set_tib)
intervals <- list()
for (i in 1:n_verification){
  ### take one verification set observation
  out2 <- out_tib 
   o3 <- out2 %>% 
     dplyr::mutate(fitted_cv =  purrr::map_dbl(.x = cross_membership, 
                                               .f = get_fitted, 
                                               fitted_vec = as.vector(unlist(pred_vals_verification_set_tib[i, 1:5])))
                   ) %>% # calculate mu hat (X_{n + 1})
     dplyr::mutate(fitted_minus_residual = fitted_cv - residual, 
                   fitted_plus_residual = fitted_cv + residual)
  ## determine quantiles - type 6?  of fitted_minus_residual and fitted_plus_residual
  intervals[[i]]<- c(quantile(o3$fitted_minus_residual, 
                              prob = alpha / 2, 
                              type = 6), 
  quantile(o3$fitted_plus_residual, 
           prob = 1 - alpha / 2, 
           type = 6)
  )
}
```


## Coverage for Trait `r x`

```{r}
mytib <- do.call("rbind", intervals) %>% 
  tibble::as_tibble() %>%
  dplyr::rename(left = 1, right = 2) %>%
  dplyr::mutate(true_pheno = pred_vals_verification_set_tib$true_pheno) %>%
  dplyr::mutate(in_interval = true_pheno <= right & true_pheno >= left) %>%
  dplyr::mutate(interval_width = right - left)
 

```

```{r}
assign(x = "out", value = mytib)
```




